Add sub-domain capability.
collabo-community/web-client pull request #11
Opened 2024-07-06 20:31 UTC by Akpjunior94

**This pull request makes the following changes**
* Added sub-domain capability to the web-client  https://discord.com/channels/1148391778492354741/1253584233155395657/1257625627691974696 

Ping @code-collabo/web-app

2024-07-09 04:17 UTC, Ifycode requested changes

2024-07-09 04:17 UTC, Ifycode commented on server.js
> +});
Ok, nice start @Akpjunior94 
Let me help you understand better. The issue description says:

#
> Make app-home page(s) run at localhost:3000

This means that 
- The main app is what should show up on `localhost:3000`
- `http://codecollabo.localhost:3000` should still not be showing main app page content, this should show the overview page of code-collabo instead.

#

> Make code-collabo page(s) run at codecollabo.localhost:3000


- e.g. using projects page as example - `http://localhost:3000/code-collabo/projects` should use this instead `http://codecollabo.localhost:3000/projects`. Right now that is saying 404 instead of displaying the required content.
- That's example with the projects page, you can do the math for the other code-collabo pages.

#

**_Also important:_** All old urls should redirect to new the domain/sub-domain URLS accordingly.

2024-07-09 15:24 UTC, Akpjunior94 commented on server.js
> +});
@Ifycode works fine for me here. i.e `http://codecollabo.localhost:3000` is showing the overview page and not the main app page content. 

Also `http://codecollabo.localhost:3000/projects` opens the project page correctly.

2024-07-09 15:24 UTC, Akpjunior94 commented on server.js
> +});
Maybe we can get on a call so you show me or a video will help me understand

2024-07-30 06:30 UTC, Akpjunior94 commented
@Ifycode I think it works based on requirement now. But i have a concern about the changes I made in the custom404PageLayout.tsx file. I feel I should remove the check for is.firstApp404Route and just do the one of the hostname instead but I left it since I don't fully understand what it is doing but I think since the routing system has changed then that should also go. What is your thought? Do let me know If I should remove it or not and I will make the necessary changes

2024-08-06 04:18 UTC, Ifycode reviewed
Hmm... What I see here looks just too complex to comment on just by looking at the code... I will have more time to look at it after Wednesday or Thursday... 
I need to finish sorting out this cohort's paid program palava. 
Nice work so far.

2024-08-14 07:02 UTC, closed without merging