FIX:Add sub-domain capability for Collabo Community App
collabo-community/web-client pull request #15
Opened 2024-08-14 06:56 UTC by Akpjunior94

#### This pull request makes the following changes

* Fixes collabo-community/issue-tickets-ready-for-fixing#2

#

#### General checklist

- [x] My pull request adheres to the [Collabo Community pull request guidelines](https://docs.collabocommunity.com/pull-request-guidelines).
- [x] I have read and understood the **Pull request guideline extension** section found at the bottom of this pull request description/body.
- [x] I have replaced the dummy text under the subheading **Testing checklist** below with the testing checklist from the issue ticket I'm working on.

#

#### Testing checklist

- [x] `app-home` page(s) run on main domain at `localhost:3000`
- [x] `code-collabo` page(s) run at `http://app.localhost:3000/page-name-goes-here`
- [ ] 404 page for `app-home` page(s) run on main domain at `localhost:3000/404`
- [ ] 404 page for `code-collabo` page(s) run at `http://app.localhost:3000/404`
- [x] The "home" redirects for app home and code-collabo pages in the nextjs config works accordingly
- [x] I certify that I ran my checklist

#

#### Pull request guideline extension

> [!NOTE]  
> Do not remove this note or section. This talks about extra things to take note of, in addition to the directions given in the Collabo Community pull request guidelines.

We appreciate the time taken to help tackle issue tickets within the Collabo Community. Please go ahead to submit your pull request even if it is not yet completed, and push to the pull request actively. This will allow us to know that you have not abandoned the issue ticket. However, you should only alert reviewers about your pull request as explained below, to avoid flooding their GitHub notifications unnecessarily.

"Ready for review" implies that things are working as expected, according to how it is specified in the issue ticket you are working on. Ensure that you test the code that you are working on, that it works as expected. Don't just request for review when your pull request is not yet done and working.

The only time you should be making people review something incomplete is: if you want to show them what's not working, so that they can send help or guidance. If this is the case, be explicit about this in our Discord community or in the comment of your pull request (after you have submitted the pull request).

2024-08-14 07:02 UTC, Akpjunior94 commented
@Ifycode as requested the PR has been transferred here. Do take not that I am still finding a work around of the remaining two unchecked test lists which are the error pages showing up correctly. 

You can still see what has been done so far while I continue working on it incase you have idea of any work around.

2024-08-18 14:23 UTC, Ifycode reviewed
Ok, what you have here actually works to the best of my understanding, although I'm still checking the implementation for the 404. I'll update you with what I think between now and tomorrow.
Well done so far @Akpjunior94

2024-08-18 15:27 UTC, Ifycode requested changes

2024-08-18 15:27 UTC, Ifycode commented on src/middleware.ts
> +  } else {
Ok I've seen the issue @Akpjunior94 
This else statement about the 404 is not needed at all.

Here's what you need to do:
- Remove this else statement and the 404 code inside, from this middleware file.
- Go to `src/modules/shared/components/Custom404PageLayout.tsx`, and first restore it to what it was initially. Then see my **explanation notes** below.

#

**Explanation notes:**
In the `src/modules/shared/components/Custom404PageLayout.tsx` file, you did this (which is a really nice start 👍🏼):
````
  const hostname = typeof window !== 'undefined' ? window.location.hostname : '';
````

Change this:
````
  const is = {
    firstApp404Route: urlStartIsAtIndexZero(firstSubAppUrlStart) && !urlStartHasMoreTextAfterItAndHasNoSlashInbetween(firstSubAppUrlStart.length),
  };
````

To: 

````
  const is = {
    firstApp404Route: hostname === 'app.localhost',
  };
````

You can then remove anything no longer used from the 404 layout file. That's all.

The structure of our application (and thanks to nextJS) has already made it easily possible this way.

2024-08-18 22:21 UTC, Ifycode requested changes

2024-08-18 22:21 UTC, Ifycode commented on package.json
> +    "express": "^4.19.2",
Is express still used? @Akpjunior94

2024-08-18 22:21 UTC, Ifycode commented on src/middleware.ts
> +  } else if (hostname === 'localhost') {
Instead of `else if` here, can this be a standalone if statement? @Akpjunior94

2024-08-18 23:11 UTC, Akpjunior94 commented on src/middleware.ts
> +  } else if (hostname === 'localhost') {
@Ifycode by standalone do you mean both condition should have if own if statement 
like
`if(hostname === 'app.localhost'){
first condition
}`

`if(hostname === 'localhost'){
second condition
}`

or you mean just an
`
if(hostname === 'app.localhost'){
second condition
}else{
the condition for the default app home - localhost
}
`

2024-08-18 23:22 UTC, Ifycode commented on src/middleware.ts
> +  } else if (hostname === 'localhost') {
The first one @AbrahamAkp

2024-08-18 23:29 UTC, Akpjunior94 commented on package.json
> +    "express": "^4.19.2",
I don't think so since we are using the middleware

2024-08-18 23:31 UTC, Ifycode commented on src/middleware.ts
> +  } else if (hostname === 'localhost') {
You can just put the if statement of main domain first/on top. Just so it's clear the app/set of pages that are top level. Just so that it's better organised.

2024-08-19 00:12 UTC, Ifycode requested changes

2024-08-19 00:12 UTC, Ifycode commented on src/modules/code-collabo/components/SideBar.tsx
> +          <Link className='app__side-menubar__navlink lib__flex-center' onClick={toggleSidebar} href='/projects'>
Both overview and project button/links take you to project page on click @Akpjunior94

2024-08-19 07:13 UTC, Akpjunior94 commented on src/modules/code-collabo/components/SideBar.tsx
> +          <Link className='app__side-menubar__navlink lib__flex-center' onClick={toggleSidebar} href='/projects'>
I think it is as a result of the changes that was made in the middleware.ts file earlier. 
<img width="621" alt="image" src="https://github.com/user-attachments/assets/e6a78d58-4fe2-4fbf-b9dc-6007d3b75a98">

fixing...

2024-08-19 07:24 UTC, Akpjunior94 commented on src/modules/code-collabo/components/SideBar.tsx
> +          <Link className='app__side-menubar__navlink lib__flex-center' onClick={toggleSidebar} href='/projects'>
Updated @Ifycode

2024-08-19 16:19 UTC, Ifycode requested changes

2024-08-19 16:19 UTC, Ifycode commented on src/modules/code-collabo/components/SideBar.tsx
> +          <Link className='app__side-menubar__navlink lib__flex-center' onClick={toggleSidebar} href='/projects'>
Yes it is @Akpjunior94 
Meaning you can just use `href='/'` instead of `href='/projects'` in the html.

Also, how do we get `/projects` to redirect to `/`, for `app.localhost` routes?

2024-08-20 00:05 UTC, Akpjunior94 commented on src/modules/code-collabo/components/SideBar.tsx
> +          <Link className='app__side-menubar__navlink lib__flex-center' onClick={toggleSidebar} href='/projects'>
I think we will need to define it in the `next.config.js` file. will push a fix for that.

2024-08-20 00:17 UTC, Akpjunior94 commented on src/modules/code-collabo/components/SideBar.tsx
> +          <Link className='app__side-menubar__navlink lib__flex-center' onClick={toggleSidebar} href='/projects'>
Updated @Ifycode

2024-08-20 10:57 UTC, Ifycode requested changes

2024-08-20 10:57 UTC, Ifycode commented on src/modules/code-collabo/components/SideBar.tsx
> +    );
This is ready to be approved. But please restore line 57 here to how it was before @Akpjunior94

2024-08-20 11:22 UTC, Akpjunior94 commented on src/modules/code-collabo/components/SideBar.tsx
> +    );
it is actually throwing lint error with red swiggle line. Restoring....

2024-08-20 11:23 UTC, Akpjunior94 commented on src/modules/code-collabo/components/SideBar.tsx
> +    );
done

2024-08-21 17:33 UTC, Ifycode approved these changes
Neatly and cleanly done. Thank you @Akpjunior94 
🙌🏽 🥳

2024-08-21 17:51 UTC, merged