FIX: Strip the Web Client of unused or no longer necessary resources
collabo-community/web-client pull request #16
Opened 2024-08-28 07:43 UTC by Akpjunior94

#### This pull request makes the following changes

* Fixes collabo-community/issue-tickets-ready-for-fixing#24

#

#### General checklist

- [x] My pull request adheres to the [Collabo Community pull request guidelines](https://docs.collabocommunity.com/pull-request-guidelines).
- [x] I have read and understood the **Pull request guideline extension** section found at the bottom of this pull request description/body.
- [x] I have replaced the dummy text under the subheading **Testing checklist** below with the testing checklist from the issue ticket I'm working on.

#

#### Testing checklist

- [x] Styled jsx configurations, and any `.js` files that contain CSS code have been removed.
- [x] Careers and donate pages in code-collabo app, and any files associated to them not used anywhere else in the application have been removed.
- [x] I certify that I ran my checklist

#

#### Pull request guideline extension

> [!NOTE]  
> Do not remove this note or section. This talks about extra things to take note of, in addition to the directions given in the Collabo Community pull request guidelines.

We appreciate the time taken to help tackle issue tickets within the Collabo Community. Please go ahead to submit your pull request even if it is not yet completed, and push to the pull request actively. This will allow us to know that you have not abandoned the issue ticket. However, you should only alert reviewers about your pull request as explained below, to avoid flooding their GitHub notifications unnecessarily.

"Ready for review" implies that things are working as expected, according to how it is specified in the issue ticket you are working on. Ensure that you test the code that you are working on, that it works as expected. Don't just request for review when your pull request is not yet done and working.

The only time you should be making people review something incomplete is: if you want to show them what's not working, so that they can send help or guidance. If this is the case, be explicit about this in our Discord community or in the comment of your pull request (after you have submitted the pull request).

2024-08-28 07:45 UTC, Akpjunior94 commented
@Ifycode I want to confirm if there is need to add `package-lock.json `file when there is removal of adding of a dependency.

2024-08-29 02:41 UTC, Ifycode commented
Don't add `package-lock.json`, that will be generated on my end later.

2024-08-29 02:42 UTC, Ifycode requested changes

2024-08-29 02:42 UTC, Ifycode commented on package.json
> -    "styled-jsx": "^5.1.2"
babel helps styled-jsx to function. So you also want to remove the babel file at the root of the repo also.

2024-08-29 02:47 UTC, Akpjunior94 commented on package.json
> -    "styled-jsx": "^5.1.2"
removing..

2024-08-29 02:59 UTC, Akpjunior94 commented on package.json
> -    "styled-jsx": "^5.1.2"
done

2024-08-29 03:16 UTC, Ifycode approved these changes

2024-08-29 03:17 UTC, merged