sidebar and Filter overlay
collabo-community/web-client pull request #5
Opened 2024-04-03 13:33 UTC by Akpjunior94

**This pull request makes the following changes**
* Fixes and adds overlay to the sidebars on mobile or smaller screen

**General checklist**
- [X] File or folder now contains changes as specified in the issue i worked on
- [X] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**
- [X] The design is responsive and implemented as stated in the issue description.
 - [X] Accessibility is left/implemented as stated in the issue description.
 - [X] Content area [right] looks and functionality is implemented as stated in the issue description
 - [X] Sidebar [left] looks and functionality is implemented as stated in the issue description
 - [X] No external library is used
 - [X] I certify that I ran my checklist
 - [X] I certify that I ran my checklist

Replace this text with the testing checklist from the issue this pull request fixes.

Ping @code-collabo/web-app

2024-04-03 13:34 UTC, Akpjunior94 commented
@Ifycode Please do have a look.

2024-04-04 03:52 UTC, Ifycode requested changes

2024-04-04 03:52 UTC, Ifycode commented on src/modules/code-collabo/components/SideBar.tsx
> +      {is_sm_screen && <div className='app__menubar-overlay' onClick={toggleSidebar}></div>}
Ok, nice first implementation @Akpjunior94 
I also like that clicking on the overlay can close the sidebar, thank you for remembering to add that though I forgot 👍🏼

#

#### 1 of 2 [Explanation]

If you now notice, we have a new convention where we don't use this anymore:
````
{is_sm_screen && <element or component />
````
As much as is possible we want to separate such checks from the location of the elements themselves, so that it is much easier to debug both right from the code in the editor or when in the dev tool.

That is why we now have a way of being plain about the screen size of the element from the name of the element. But then the check for null or not is within the component.

#

#### 2 of 2 [Suggestion]

Towards the end of this `sidebar` file, you will see an export for `SM_Screen_SideBarComponent`.

In the if statement, you will find sidebar in there. The checks are already in place and implemented as you can see, so you don't need to do checks again. 
Just try adding adding your overlay element on top of the sidebar that you find in that if statement, and see the "magic" that happens.

2024-04-04 04:34 UTC, Akpjunior94 commented on src/modules/code-collabo/components/SideBar.tsx
> +      {is_sm_screen && <div className='app__menubar-overlay' onClick={toggleSidebar}></div>}
oh okay cool. I will try that and see

2024-04-04 11:39 UTC, Akpjunior94 commented on src/modules/code-collabo/components/SideBar.tsx
> +      {is_sm_screen && <div className='app__menubar-overlay' onClick={toggleSidebar}></div>}
Truly I saw magic happened. Make sense

2024-04-04 15:18 UTC, Ifycode approved these changes
Awesome. Thank you!

2024-04-04 15:19 UTC, Ifycode commented on src/modules/code-collabo/components/SideBar.tsx
> +      {is_sm_screen && <div className='app__menubar-overlay' onClick={toggleSidebar}></div>}
😂

2024-04-04 15:22 UTC, merged