Maintaining 3-column header structure
collabo-community/web-client pull request #6
Opened 2024-04-07 20:31 UTC by Akpjunior94

**This pull request makes the following changes**
* Fixes the Header pageTitle not centralising on mobile as a result of the filter element not showing up on other pages.

**General checklist**
- [X] File or folder now contains changes as specified in the issue i worked on
- [X] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**
- [X] The design is responsive and implemented as stated in the issue description.
 - [X] Accessibility is left/implemented as stated in the issue description.
 - [X] Content area [right] looks and functionality is implemented as stated in the issue description
 - [X] Sidebar [left] looks and functionality is implemented as stated in the issue description
 - [X] No external library is used
 - [X] I certify that I ran my checklist
 - [X] I certify that I ran my checklist

Replace this text with the testing checklist from the issue this pull request fixes.

Ping @code-collabo/web-app

2024-04-07 20:35 UTC, Akpjunior94 commented
@Ifycode I went the css route. my naming might not be the best 😆 I also had to move some logic up the tree in other to reuse it. Please have a look.

2024-04-10 10:50 UTC, Ifycode requested changes

2024-04-10 10:50 UTC, Ifycode commented on src/modules/code-collabo/components/AppPage.tsx
> +  const three_column_structure = isProjectPage ? 'lib__flex-space-btw__sm' : 'app__header-column'
Nice try.

But we don't need a check for the styles, it makes it complicated @Akpjunior94 
All we need is just one style that works for whether the filter toggle button is present in the header or not (for smaller devices).
More like a "one-size-fits-all" CSS solution

2024-04-30 12:44 UTC, Ifycode requested changes

2024-04-30 12:44 UTC, Ifycode commented on src/modules/code-collabo/components/SM_Screen_Filter.tsx
> +
Please restore the space here @Akpjunior94

2024-04-30 12:44 UTC, Ifycode commented on src/modules/code-collabo/components/AppPage.tsx
> +        <header className={`app__header lib__flex-space-btw__sm app__header-fit-all`}>
`className=''` instead of `className={``}` since no js involved.

2024-04-30 12:44 UTC, Ifycode commented on src/modules/code-collabo/styles/app.main.js
> +        justify-items: center;
Let's not have a separate class `app__header-fit-all`
The styles here can be added directly inside the `app-header` class which is already existing.

2024-06-28 12:33 UTC, Ifycode commented
Closing PR for more research on this by me.

2024-06-28 12:33 UTC, closed without merging